apiVersion: v1
kind: Secret
metadata:
  name: workervotacaosecret
type: Opaque
data:
  UsernameKafka: $ConnectionString
  PasswordKafka: <CONNECTION STRING DO AZURE EVENT HUBS EM BASE 64>
  SaslKafka: plaintext
  TlsKafka: enable